In [1]:
import pandas as pd
import numpy as np

In [36]:
dataframe = pd.read_csv('Salaries.csv')

In [35]:
print(dataframe)

           yearID teamID lgID    salary
playerID                               
barkele01    1985    ATL   NL    870000
benedbr01    1985    ATL   NL    545000
campri01     1985    ATL   NL    633333
ceronri01    1985    ATL   NL    625000
chambch01    1985    ATL   NL    800000
...           ...    ...  ...       ...
treinbl01    2015    WAS   NL    512800
ugglada01    2015    WAS   NL    507500
werthja01    2015    WAS   NL  21000000
zimmejo02    2015    WAS   NL  16500000
zimmery01    2015    WAS   NL  14000000

[25574 rows x 4 columns]


In [34]:
dataframe2 = pd.read_csv('Salaries.csv', index_col='playerID', header=0, skiprows=[2])
print(dataframe2.head())
print(dataframe2.index.name)

           yearID teamID lgID  salary
playerID                             
barkele01    1985    ATL   NL  870000
benedbr01    1985    ATL   NL  545000
campri01     1985    ATL   NL  633333
ceronri01    1985    ATL   NL  625000
chambch01    1985    ATL   NL  800000
playerID


In [38]:
atl = dataframe[dataframe['teamID'] == 'ATL']['salary']
d = atl.describe()
d.loc[['std','25%','50%','75%','mean','max','min']]

std     3.432673e+06
25%     3.000000e+05
50%     6.000000e+05
75%     2.390625e+06
mean    2.206239e+06
max     1.606180e+07
min     6.000000e+04
Name: salary, dtype: float64

In [43]:
# Create a Python dictionary object whose keys are the headers of the dataframe
# created in the read_csv() exercise and values are Python list objects that contain
# data corresponding to the headers

dictionary = dataframe.head().to_dict(orient='list')
print(dictionary)

{'yearID': [1985, 1985, 1985, 1985, 1985], 'teamID': ['ATL', 'ATL', 'ATL', 'ATL', 'ATL'], 'lgID': ['NL', 'NL', 'NL', 'NL', 'NL'], 'playerID': ['barkele01', 'bedrost01', 'benedbr01', 'campri01', 'ceronri01'], 'salary': [870000, 550000, 545000, 633333, 625000]}


In [48]:
#Create a dataframe using pd.DataFrameRead (
#Documentation Link ) and from the dictionary created in (e). Then, change the header to "a", "b", "c",
df = pd.DataFrame(dictionary)
df.columns = ['a','b','c','d','e']
print(df)

      a    b   c          d       e
0  1985  ATL  NL  barkele01  870000
1  1985  ATL  NL  bedrost01  550000
2  1985  ATL  NL  benedbr01  545000
3  1985  ATL  NL   campri01  633333
4  1985  ATL  NL  ceronri01  625000


5) Numpy!

In [49]:
# Create a 2-dimensional Python list object, then convert it to a Numpy array
# object.
list2d = [[1,2,3],[4,5,6],[7,8,9]]
array2d = np.array(list2d)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Examine the ndim, shape, size, dtype, itemsize, and data attributes of the numpy
# array object. Make sure you understand their functions

ndim → number of axes (dimensions). For a 3×3 matrix it’s 2.

shape → tuple of lengths along each axis. Here (3, 3) = 3 rows × 3 cols.

size → total number of elements. Here 9.

dtype → element data type (e.g., int32, float64).

itemsize → bytes per element. int32 → 4 bytes; float64 → 8 bytes.

data → a pointer-like buffer reference to the array’s memory (rarely used directly).

FYI: nbytes (total bytes in the data buffer) = size * itemsize. In the demo, casting to float64 doubled itemsize and thus nbytes.

In [61]:
# Learn the dimension concept of an ndarray object by using reshape() and flatten()
# methods
a = list(range(1,13))
a = np.array(a)
a.shape = (3,4)
print(a)

b = a.reshape(2,6)
print(b.ndim)
print(b)

c = b.flatten()
print(c)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [71]:
# Understand how the slice operation works for 1-D arrays and 2-D arrays and practice by yourself
s = "abcdef"
s[1:4]      # 'bcd'   (from index 1 up to, not including, 4)
s[:3]       # 'abc'   (start default is 0)
s[3:]       # 'def'   (stop default is end)
s[::2]      # 'ace'   (step of 2)
s[::-1]     # 'fedcba' (negative step = reverse)

a = list(range(1,13))
a = np.array(a)

b = a[:4]
print(b)

a = a.reshape(3,4)
c = a[1:]
print(c)
d = a[::-1]
print(d)
e = a[1:3, :3]
print(e)

[1 2 3 4]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 5  6  7]
 [ 9 10 11]]


Learn operations on ndarray by examining the argmin(), argmax(), min(), max(),
mean(), sum(), std(), dot(), square(), sqrt(), abs(). exp(), sign(), and mod()
methods


Reductions (whole array or by axis)

A.min(), A.max(), A.mean(), A.sum(), A.std() → single numbers over all elements.

By axis: A.min(axis=0) (per column), A.min(axis=1) (per row).

Sample std: A.std(ddof=1); population std (default): ddof=0.

Indices of extrema

A.argmin() / A.argmax() → flat index of min/max (as if A.ravel()).

Convert to 2D index: np.unravel_index(A.argmin(), A.shape).

Axis-wise: A.argmin(axis=0) (index within each column), etc.

Dot products & matrix multiply

Vectors: np.dot(v, w) (or v @ w) → scalar dot product.

Matrices: A @ A.T → matrix multiply (shape rules apply: (m×n) @ (n×k) → (m×k)).

Elementwise ufuncs (broadcast to each element)

np.square(A) ↔ A**2

np.sqrt(A) (use np.sqrt(np.clip(A, 0, None)) if negatives present)

np.abs(A)

np.exp(A)

np.sign(A) → -1/0/1 by element

np.mod(A, 3) ↔ A % 3 (remainder; non-negative results)

In [72]:
# Per-column stats
col_means = a.mean(axis=0)
print(col_means)

# Where is the global min?
amin_idx = np.unravel_index(a.argmin(), a.shape)
print(amin_idx)

# Normalize each column (z-score)
Z = (a - a.mean(axis=0)) / a.std(axis=0, ddof=1)
print(Z)

# Safe sqrt for mixed-sign arrays
root = np.sqrt(np.clip(a, 0, None))
print(root)

Examine the arange(), ones(), zeros(), eye(), linspace(), and concatenate() meth-
ods. Make yourself comfortable with these methods

#️⃣ np.arange(start, stop, step)
Ranges with a fixed step; excludes stop. Be careful with floats (rounding); for evenly spaced floats, prefer linspace.

1️⃣ np.ones(shape[, dtype]) / np.zeros(shape[, dtype])
Fill arrays with 1s or 0s. Use ones_like/zeros_like(other) to match another array’s shape/dtype.

🧾 np.eye(N[, M, k])
Identity/diagonal matrix. k shifts the diagonal (k=1 above main, k=-1 below).

📏 np.linspace(start, stop, num[, endpoint, retstep])
Exactly num evenly spaced samples between start and stop. endpoint=False drops the stop value; retstep=True returns the step size.

🔗 np.concatenate((a, b, ...), axis=...)
Glues arrays along an axis. Shapes must match on all other axes.

Rows: axis=0 (stack more rows)

Columns: axis=1 (stack more columns)
For convenience wrappers, see np.stack, np.vstack, np.hstack.

6) Scikit-Learn
This section introduces some packages (or methods) in Python (Scikit-Learn and Scipy)
that will be frequently used in your programming assignments. You must become
familiar with them and use them masterfully.
•
Data Preprocessing (
Documentation Link
)
–
Standardization: StandardScaler
–
Normalization: MinMaxScaler
–
Quantifying Categorical Features: LabelEncoder. OneHotEncoder
–
Construct Train and Test Sets: model_selection.train_test_split
•
KNN:KNeighborsClassifier
•
Linear Regression: LinearRegression

Homework 0 DSCI 552, Instructor: Mohammad Reza Rajati
•
Logistic Regression: LogisticRegression, LogisticRegressionCV
•
Feature Selection / Model Selection
–
L1 Penalized Regression (Lasso Regression) with Cross-Validation: LassoCV
–
L2 Penalized Regression (Ridge Regression) with Cross-Validation: RidgeCV
–
Cross-Validation: StratifiedKFold, RepeatedKFold, LeaveOneOut, KFold,
model_selection.cross_validate, model_selection.cross_val_predict,
model_selection.cross_val_score
–
Model Metrics (
Documentation Link
): accuracy_score, auc, f1_score,
hamming_loss, precision_score, recall_score, roc_auc_score
•
Decision Tree: DecisionTreeClassifier, DecisionTreeRegressor
•
Bootstrap, Ensemble Methods
–
Bootstrap: bootstrapped (
Documentation Link
)
–
Bagging: RandomForestClassifier, RandomForestRegressor
–
Boosting: AdaBoostClassifier, AdaBoostRegressor
•
Support Vector Machines (
Documentation Link
): LinearSVC, LinearSVR
•
Multiclass and Multilabel Classification (
Documentation Link
)
–
One-vs-one Multiclass Strategy: OneVsOneClassifier
–
One-vs-the-rest (OvR) multiclass/multilabel strategy / OneVsRestClassifier
•
Unsupervised Learning
–
K-means Clustering: KMeans
–
Hierarchical Clustering: scipy.cluster.hierarchy (not scikit-learn)
•
Semi-supervised Learning (
Documentation Link
)

7.
Git and GitHub

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
# you've already mounted drive at /content/drive
%cd "/content/drive/MyDrive/Colab Notebooks"
!ls -1 HW0.ipynb                               # confirm the notebook is here

/content/drive/MyDrive/Colab Notebooks
HW0.ipynb


In [8]:
!git init -b master || (git init && git checkout -b master)
!git config user.name  "JC"
!git config user.email "cargasac@usc.edu"
!printf ".ipynb_checkpoints/\n__pycache__/\n*.pyc\n.DS_Store\n" > .gitignore



Initialized empty Git repository in /content/drive/MyDrive/Colab Notebooks/.git/
Switched to a new branch 'dev'
[dev (root-commit) 1b090e2] Add HW0 notebook on dev branch
 2 files changed, 5 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 HW0.ipynb


In [ ]:
!git checkout -b dev
!git add "HW0.ipynb" .gitignore
!git commit -m "Add HW0 notebook on dev branch"

In [10]:
#C) merge dev into master
!git branch --list
!git branch master          # create master at the current commit
!git checkout master        # switch to master
!git merge --no-ff dev -m "Merge dev into master"   # will likely say 'Already up to date' (that’s fine)
!git branch -vv


* dev
M	HW0.ipynb
Switched to branch 'master'
Already up to date.
  dev    1b090e2 Add HW0 notebook on dev branch
* master 1b090e2 Add HW0 notebook on dev branch


In [11]:
# e) Push the changes to a new repository made in github
# replace URL with your repo URL (HTTPS shown)
!git remote add origin https://github.com/SpoonLegends/tmp-colab-hw0.git
!git push -u origin master


fatal: could not read Username for 'https://github.com': No such device or address
